defaults:
    - /optimizer: adam.yaml

_target_: emulator.src.core.models.archesclimate.ArchesClimate
logger:
    wandb:
        project: "archesclimate_climateset"
        offline: True
scheduler:
    _target_: emulator.src.utils.lr_scheduler.LinearWarmupCosineAnnealingLR
    warmup_epochs: 5 #original specs
    max_epochs: 50 #original specs
    warmup_start_lr: 1e-8
    eta_min: 1e-8
module: 
    pretrained_path: ${work_dir}/emulator/checkpoints/epoch=99-step=5900.ckpt
    backbone:
    # default backbone
        _target_: geoarches.backbones.archesweather.ArchesWeatherCondBackbone
        tensor_size: [1,48,72] # after embed
        emb_dim: 384
        cond_dim: 512
        window_size: [1, 6, 10]
        droppath_coeff: 0.2
        dropout: 0
        depth_multiplier: 2
        use_skip: False
        first_interaction_layer: False
        axis_attn: False
        mlp_layer: swiglu
        mlp_ratio: 4.0
    embedder: 
        _target_: DecadeCast.model.climateset_encoder_decoder.ClimateSetEncodeDecodeLayer
        surface_ch: 48 
        img_size: [48,96,144]
        emb_dim: 384
        out_emb_dim: 384
        patch_size: [2, 2, 2]
        n_concatenated_states: 1